package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

type essay struct {
	Slug       string
	Title      string
	Book       string
	Part       int
	PartTitle  string
	Order      int
	Hook       string
	HiddenMath string
}

func allEssays() []essay {
	return []essay{
		// Book I, Part 1: Everything Is a Rate of Change
		{"snap-crackle-pop", "Snap, Crackle, and Pop", "I", 1, "Everything Is a Rate of Change", 1, "Riding an elevator; catching an egg", "The derivative chain extends to the 6th order and your body feels all of them"},
		{"derivative-chains", "Derivative Chains in Everyday Life", "I", 1, "Everything Is a Rate of Change", 2, "Inflation, glucose monitors, faucets, loudness", "30+ familiar quantities form derivative chains across physics, economics, biology"},
		{"euler-spiral-onramps", "The Euler Spiral in Highway On-Ramps", "I", 1, "Everything Is a Rate of Change", 3, "Merging onto the highway without jerking the wheel", "Clothoid spirals have linearly increasing curvature for zero jerk"},

		// Book I, Part 2: Your Body Already Knows
		{"log-scale-senses", "The Log Scale of Your Senses", "I", 2, "Your Body Already Knows", 1, "Why a 100W bulb doesn't look twice as bright as 50W", "Weber-Fechner law: perception scales logarithmically with stimulus"},
		{"fourier-transform-ear", "The Fourier Transform in Your Ear", "I", 2, "Your Body Already Knows", 2, "Hearing a chord and picking out individual notes", "Your cochlea performs a real-time Fourier decomposition"},
		{"color-perception", "The Mathematics of Color Perception", "I", 2, "Your Body Already Knows", 3, "Mixing watercolors; picking a paint swatch", "Human color vision is 3-dimensional. There is no brown light."},
		{"single-photon-vision", "Why Your Eyes Can Detect a Single Photon", "I", 2, "Your Body Already Knows", 4, "Seeing in near-total darkness", "Rod cells perform near-optimal Bayesian inference to detect single photons"},

		// Book I, Part 3: What Your Kitchen Knows
		{"cheerios-effect", "The Cheerios Effect", "I", 3, "What Your Kitchen Knows", 1, "Cereal pieces clump together in milk", "Meniscus deformation creates gravitational potential wells via the Laplace equation"},
		{"coffee-ring-effect", "The Coffee Ring Effect", "I", 3, "What Your Kitchen Knows", 2, "A dried coffee drop leaves a dark ring", "Pinned contact lines and edge-dominant evaporation carry particles to the rim"},
		{"shower-curtain", "Why Your Shower Curtain Blows Inward", "I", 3, "What Your Kitchen Knows", 3, "The curtain billows toward you", "The Bernoulli explanation is wrong. A horizontal vortex generated by the spray sucks it in."},
		{"soap-bubbles", "The Geometry of Soap Bubbles", "I", 3, "What Your Kitchen Knows", 4, "Blowing bubbles in the backyard", "A bubble is a perfect minimal surface. Double bubbles were not proved optimal until 2002."},
		{"ice-slipperiness", "Why Ice Is Slippery", "I", 3, "What Your Kitchen Knows", 5, "Ice is slippery", "The Victorian pressure-melting explanation is wrong by orders of magnitude. Still unsolved."},
		{"mpemba-effect", "The Mpemba Effect", "I", 3, "What Your Kitchen Knows", 6, "Hot water can freeze faster than cold water", "Observed by Aristotle, named for a Tanzanian schoolboy, still not fully explained"},

		// Book I, Part 4: What Nature Computed
		{"hexagons-beehives", "Why Hexagons in Beehives", "I", 4, "What Nature Computed", 1, "Honeycomb structure", "Hexagons partition area with the least total perimeter. Proved 1999."},
		{"fibonacci-sunflowers", "The Fibonacci Spiral in Sunflowers", "I", 4, "What Nature Computed", 2, "Counting petals, gazing at seed heads", "Seeds arrange at the golden angle producing Fibonacci spirals that optimize packing"},
		{"turing-patterns", "How Leopards Get Spots", "I", 4, "What Nature Computed", 3, "Animal patterns: spots, stripes, spirals", "Turing patterns from reaction-diffusion: two chemicals at different rates create spots and stripes"},
		{"constructal-law", "Why Rivers Look Like Lungs", "I", 4, "What Nature Computed", 4, "River deltas, bronchial trees, lightning bolts branch the same way", "Flow systems evolve toward tree architectures that minimize global resistance"},
		{"starling-murmurations", "Starling Murmurations", "I", 4, "What Nature Computed", 5, "Thousands of starlings moving as one at sunset", "Scale-free correlations: the flock is poised at a phase transition"},

		// Book I, Part 5: Hidden in Plain Sight
		{"catenary", "The Catenary in Every Necklace and Power Line", "I", 5, "Hidden in Plain Sight", 1, "A chain hanging between your collarbones", "Not a parabola. It is cosh(x). Galileo got it wrong."},
		{"wave-equation-pond", "The Wave Equation in a Pond", "I", 5, "Hidden in Plain Sight", 2, "Dropping a pebble and watching ripples spread", "Circular waves and interference governed by the 2D wave equation"},
		{"ghost-waves", "Why Deep-Water Waves Are Ghosts", "I", 5, "Hidden in Plain Sight", 3, "Watching ocean swells", "Crests travel at twice the speed of the energy group and vanish at the front"},
		{"mud-cracks", "Why Mud Cracks in Patterns", "I", 5, "Hidden in Plain Sight", 4, "Dried puddles, cracked earth", "Crack networks encode drying history. Sequential cracking yields 4-sided polygons."},
		{"chladni-figures", "Chladni Figures: Seeing Sound", "I", 5, "Hidden in Plain Sight", 5, "Sand on a vibrating plate organizes into geometry", "Sand settles on nodal lines: the zeros of the eigenfunctions of the Laplacian"},

		// Book I, Part 6: The Mathematics of Beautiful Things
		{"musical-consonance", "Musical Consonance and Small Fractions", "I", 6, "The Mathematics of Beautiful Things", 1, "Why a lullaby sounds sweet", "Consonant intervals are small-fraction frequency ratios: 2:1, 3:2, 4:3"},
		{"imperfect-piano", "Why a Piano Can Never Be Perfectly in Tune", "I", 6, "The Mathematics of Beautiful Things", 2, "Piano tuning", "The 12th root of 2 approximates but never equals 3/2. That gap haunts all of Western music."},
		{"islamic-tessellations", "Tessellations in Islamic Art", "I", 6, "The Mathematics of Beautiful Things", 3, "Geometric patterns in mosques and palaces", "Girih tiles in 15th-century Isfahan contain quasicrystalline Penrose-like patterns"},
		{"hyperbolic-crochet", "Hyperbolic Crochet", "I", 6, "The Mathematics of Beautiful Things", 4, "A grandmother crocheting a ruffled scarf", "The only way to make a physical model of hyperbolic space is crochet"},
		{"math-of-braiding", "The Mathematics of Braiding", "I", 6, "The Mathematics of Beautiful Things", 5, "French braids, challah bread, maypole ribbons", "Braid theory: the Artin braid group classifies braids algebraically"},
		{"origami-geometry", "The Geometry of Origami", "I", 6, "The Mathematics of Beautiful Things", 6, "Folding a paper crane", "Origami obeys the Huzita-Hatori axioms and can solve cubic equations"},

		// Book I, Part 7: The Mathematics of Living Together
		{"arrows-impossibility", "Arrow's Impossibility Theorem", "I", 7, "The Mathematics of Living Together", 1, "Choosing among three or more candidates", "No ranked voting system can satisfy unanimity, IIA, and non-dictatorship simultaneously"},
		{"fair-cake-cutting", "The Mathematics of Fair Cake-Cutting", "I", 7, "The Mathematics of Living Together", 2, "Splitting dessert so everyone is happy", "Envy-free division for n people was not solved until 2016"},
		{"prisoners-dilemma-traffic", "The Prisoner's Dilemma in Traffic", "I", 7, "The Mathematics of Living Together", 3, "Merging lanes: cooperate or cut in?", "Zipper merging is a Nash equilibrium. Every traffic jam is a game-theory experiment."},
		{"queuing-grocery", "Queuing Theory at the Grocery Store", "I", 7, "The Mathematics of Living Together", 4, "Choosing the fastest checkout line", "Poisson processes and Little's Law. One serpentine line beats multiple lines."},

		// Book I, Part 8: What Holds the Cosmos Together
		{"berry-phase-foucault", "The Berry Phase and the Foucault Pendulum", "I", 8, "What Holds the Cosmos Together", 1, "A Foucault pendulum's plane of swing rotates", "The rotation is geometric phase: parallel transport on a curved surface"},
		{"gps-relativity", "GPS Is Applied Relativity", "I", 8, "What Holds the Cosmos Together", 2, "Getting driving directions on your phone", "Without Einstein's corrections, GPS position would drift 10 km per day"},
		{"kam-theorem", "The KAM Theorem: Why the Solar System Survives", "I", 8, "What Holds the Cosmos Together", 3, "Planets orbit stably despite perturbations", "Irrational frequency ratios prevent resonant energy accumulation"},

		// Book I, Epilogue
		{"math-at-movies", "Mathematics at the Movies", "I", 9, "Epilogue", 1, "How cinema treats mathematics", "Five films that honored math, five that assaulted it"},

		// Book II, Part 1: The Numbers Behind the Numbers
		{"benfords-law", "Benford's Law", "II", 1, "The Numbers Behind the Numbers", 1, "Leading digits of financial data", "The first digit is 1 about 30 percent of the time. Used to detect fraud."},
		{"pareto-distribution", "The Pareto Distribution", "II", 1, "The Numbers Behind the Numbers", 2, "You wear 20 percent of your clothes 80 percent of the time", "Power laws in wealth, word frequency, city sizes, website traffic"},
		{"exponential-growth", "Exponential Growth and Your Intuition", "II", 1, "The Numbers Behind the Numbers", 3, "COVID spread, compound interest, lily pads", "Humans think linearly. The pond is half-empty one day before it is full."},
		{"shuffling-seven-times", "Why Shuffling Seven Times Is Enough", "II", 1, "The Numbers Behind the Numbers", 4, "Shuffling a deck of cards", "Riffle shuffles undergo a sharp phase transition at exactly 7 shuffles"},
		{"kleibers-law", "Kleiber's Law", "II", 1, "The Numbers Behind the Numbers", 5, "Big animals live longer with slower heartbeats", "Metabolic rate scales as M to the 3/4. A mouse and elephant get the same number of heartbeats."},

		// Book II, Part 2: Probability Against Intuition
		{"monty-hall", "The Monty Hall Problem", "II", 2, "Probability Against Intuition", 1, "Do you want to switch doors?", "Conditional probability and Bayes' theorem in a TV game show"},
		{"bayes-doctor", "Bayes' Theorem at the Doctor's Office", "II", 2, "Probability Against Intuition", 2, "A positive test result", "A 99 percent accurate test has a high false positive rate if the disease is rare"},
		{"regression-to-mean", "Regression to the Mean", "II", 2, "Probability Against Intuition", 3, "Feeling better after taking a supplement", "Extreme measurements naturally drift toward the average on retest"},
		{"secretary-problem", "The Secretary Problem", "II", 2, "Probability Against Intuition", 4, "How many candidates to interview before committing", "Interview 37 percent then hire the next one better than all seen so far"},
		{"birthday-paradox", "The Birthday Paradox", "II", 2, "Probability Against Intuition", 5, "No way two of us share a birthday!", "In 23 people there is a greater than 50 percent chance of a shared birthday"},

		// Book II, Part 3: Shape and Space
		{"coffee-mug-topology", "The Topology of Your Coffee Mug", "II", 3, "Shape and Space", 1, "A donut and a coffee mug are the same shape", "Topology classifies shapes by holes, not angles"},
		{"packing-oranges", "Packing Oranges", "II", 3, "Shape and Space", 2, "Stacking fruit in a pyramid", "Kepler's conjecture proved in 2017: face-centered cubic is optimal"},
		{"voronoi-diagrams", "Voronoi Diagrams", "II", 3, "Shape and Space", 3, "Which coffee shop is closest?", "Voronoi tessellation partitions space by nearest neighbor"},
		{"eulers-bridges", "Euler's Bridges and the Birth of Topology", "II", 3, "Shape and Space", 4, "Crossing all seven bridges without repeating", "The first theorem of graph theory. Counting odd-degree vertices."},
		{"hairy-ball-theorem", "Why You Can't Comb a Coconut", "II", 3, "Shape and Space", 5, "Smoothing hair on a sphere", "Every continuous vector field on a sphere has at least one zero"},

		// Book II, Part 4: Signals and Information
		{"shannon-entropy", "Shannon Entropy", "II", 4, "Signals and Information", 1, "Autocomplete predicting your next word", "Information theory quantifies surprise. English has about 1.3 bits per character."},
		{"nyquist-sampling", "Nyquist Sampling in Digital Music", "II", 4, "Signals and Information", 2, "Why CDs use 44100 samples per second", "To capture 20 kHz you must sample at more than 40 kHz"},
		{"eulers-formula-ac", "Euler's Formula in AC Power", "II", 4, "Signals and Information", 3, "Plugging anything into a wall outlet", "AC is modeled with e^(i*omega*t). Imaginary numbers in your walls."},
		{"markov-chains", "Markov Chains in the Weather Forecast", "II", 4, "Signals and Information", 4, "40 percent chance of rain tomorrow", "Tomorrow depends on today but not on last week"},

		// Book II, Part 5: Optimization and the Impossible
		{"traveling-salesman", "The Traveling Salesman", "II", 5, "Optimization and the Impossible", 1, "Planning the most efficient errand route", "NP-hard: 15 stops requires 653 billion route comparisons"},
		{"kelly-criterion", "The Kelly Criterion", "II", 5, "Optimization and the Impossible", 2, "Deciding how much to wager", "Information theory gives an optimal bet size. Overbetting guarantees ruin."},
		{"brachistochrone", "The Brachistochrone", "II", 5, "Optimization and the Impossible", 3, "The fastest path down a ramp", "The cycloid solves the fastest-descent problem via calculus of variations"},
		{"amdahls-law", "Amdahl's Law", "II", 5, "Optimization and the Impossible", 4, "Trying to get ready faster by parallelizing", "Speedup is limited by the serial fraction. Too many cooks."},
		{"gerrymandering", "Gerrymandering and the Shape of Fairness", "II", 5, "Optimization and the Impossible", 5, "Drawing voting district boundaries", "Compactness metrics and efficiency gaps detect manipulation"},

		// Book II, Part 6: The Gentle Curves
		{"logarithmic-spiral-seashells", "The Logarithmic Spiral of Seashells", "II", 6, "The Gentle Curves", 1, "Holding a nautilus shell", "The shell grows but never changes shape: a logarithmic spiral"},
		{"pursuit-curves", "Curves of Pursuit: Kittens Chasing", "II", 6, "The Gentle Curves", 2, "Four kittens at corners each walking toward the next", "They spiral inward on a logarithmic curve to convergence"},
		{"lissajous-curves", "Lissajous Curves in Pendulum Art", "II", 6, "The Gentle Curves", 3, "A sand pendulum drawing patterns", "Frequency ratios create ellipses, figure-eights, and delicate knots"},
		{"spirograph", "Spirograph and Epicycloids", "II", 6, "The Gentle Curves", 4, "The Spirograph toy", "Circles rolling inside circles: Ptolemy's math in a children's toy"},
		{"arbelos", "The Arbelos of Archimedes", "II", 6, "The Gentle Curves", 5, "Semicircles nested within semicircles", "Crescent shapes with astonishingly elegant area properties"},

		// Book II, Part 7: Nature's Other Ledger
		{"aspens-tremble", "Why Aspens Tremble", "II", 7, "Nature's Other Ledger", 1, "Quaking aspens shiver in the slightest breeze", "The flattened petiole gives a resonant flutter frequency: an eigenvalue problem"},
		{"vines-twist", "How Vines Know to Twist", "II", 7, "Nature's Other Ledger", 2, "A morning glory spiraling up a pole", "Helical geometry on a cylinder with genetically fixed chirality"},
		{"spider-silk", "Why Spider Silk Outperforms Steel", "II", 7, "Nature's Other Ledger", 3, "A spider web catching a fly", "Multi-objective optimization: strength, toughness, weight, construction cost"},
		{"wax-moth-ears", "Why Wax Moths Have the Best Ears", "II", 7, "Nature's Other Ledger", 4, "A moth hearing 300 kHz", "Acoustic impedance matching at medical-ultrasound frequencies in a 12mm ear"},
		{"diffusion-perfume", "The Diffusion Equation in Perfume", "II", 7, "Nature's Other Ledger", 5, "A scent filling a room", "Fick's laws: concentration follows a widening Gaussian bell curve"},

		// Book II, Part 8: The Open Frontier
		{"navier-stokes", "Navier-Stokes: Pouring Honey Is Unsolved", "II", 8, "The Open Frontier", 1, "Pouring honey off a spoon", "A Millennium Prize problem. Nature computes solutions we cannot prove are solvable."},
		{"hear-shape-drum", "Can One Hear the Shape of a Drum?", "II", 8, "The Open Frontier", 2, "Tapping a drumhead and hearing its tone", "You can hear topology (holes) but not exact geometry"},
		{"buffons-noodle", "Buffon's Noodle", "II", 8, "The Open Frontier", 3, "Dropping a curved needle on lined paper", "Probability depends only on total length, not shape"},
		{"ham-sandwich", "The Ham Sandwich Theorem", "II", 8, "The Open Frontier", 4, "Slicing a sandwich with one cut", "One planar cut bisects bread, ham, and cheese simultaneously no matter how they are arranged"},
		{"self-organized-criticality", "Self-Organized Criticality", "II", 8, "The Open Frontier", 5, "A sandpile grows until it avalanches", "The pile drives itself to a critical state with power-law avalanches"},
		{"banach-tarski", "The Banach-Tarski Paradox", "II", 8, "The Open Frontier", 6, "Cutting a ball into pieces", "Using the axiom of choice, reassemble one sphere into two of the same size"},
		{"cat-geometric-phase", "Why Cats Land on Their Feet", "II", 8, "The Open Frontier", 7, "A cat dropped upside-down rotates 180 degrees", "Zero angular momentum rotation via geometric phase on a fiber bundle"},
		{"unreasonable-effectiveness", "The Unreasonable Effectiveness of Mathematics", "II", 8, "The Open Frontier", 8, "Why does math work at all?", "Wigner's 1960 essay: the deep mystery is that equations describe nature at all"},

		// Reserve Pool
		{"snowflakes", "Symmetry in Snowflakes", "R", 0, "Reserve", 1, "Catching a snowflake on a mitten", "Six-fold symmetry from hexagonal crystal lattice. Group theory made visible."},
		{"random-walks", "Random Walks on Your Stock Portfolio", "R", 0, "Reserve", 2, "Day-to-day stock price changes", "Brownian motion and the Wiener process"},
		{"mobius-strip", "The Mobius Strip", "R", 0, "Reserve", 3, "Twisting a strip of gift wrap", "One side, one edge. Cut it down the middle and get one longer strip."},
		{"watercolor-blooms", "The Mathematics of Watercolor Blooms", "R", 0, "Reserve", 4, "Wet-on-wet painting", "Rayleigh-Taylor instability in miniature"},
		{"bell-curve-wildflowers", "The Bell Curve in a Wildflower Meadow", "R", 0, "Reserve", 5, "Flower heights and petal sizes", "Central Limit Theorem: many small random influences yield a Gaussian"},
		{"doppler-effect", "The Doppler Effect", "R", 0, "Reserve", 6, "The pitch of a siren changing", "Relativistic frequency shifting from ambulances to redshift"},
		{"optimal-transport", "Optimal Transport", "R", 0, "Reserve", 7, "Moving a pile of sand to fill holes", "Monge 1781 to Kantorovich 1942 to modern machine learning"},
		{"central-limit-baking", "The Central Limit Theorem in Baking", "R", 0, "Reserve", 8, "Why cookies come out roughly the same", "Average of many small errors converges to normal"},
		{"tessellations-bathroom", "Tessellations in Your Bathroom Floor", "R", 0, "Reserve", 9, "Tiling a floor without gaps", "Only three regular polygons tile the plane"},
		{"graph-theory-social", "Graph Theory in Social Networks", "R", 0, "Reserve", 10, "Six degrees of separation", "Small-world networks and Erdos-Renyi models"},
		{"sine-waves-tides", "Sine Waves in Ocean Tides", "R", 0, "Reserve", 11, "Watching the tide come in", "Tidal harmonics: superposition of sine waves"},
		{"fractals-broccoli", "Fractals in Broccoli", "R", 0, "Reserve", 12, "Romanesco self-similar structure", "Fractal geometry with non-integer dimensions"},
		{"coastline-paradox", "The Coastline Paradox", "R", 0, "Reserve", 13, "Measuring a country's border", "Length diverges to infinity as ruler shrinks"},
		{"algorithms-blind-spots", "Why Algorithms Have Blind Spots", "R", 0, "Reserve", 14, "AI making wrong decisions", "Godel's incompleteness applied to computation"},
		{"zenos-paradox", "Why Zeno Was Wrong", "R", 0, "Reserve", 15, "Achilles and the tortoise", "Convergent infinite series took 2000 years to formalize"},
	}
}

func main() {
	baseDir := "pipeline/ideas"

	if err := os.MkdirAll(baseDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating directory: %v\n", err)
		os.Exit(1)
	}

	now := time.Now().Format("2006-01-02")
	essays := allEssays()

	for _, e := range essays {
		ideaContent := fmt.Sprintf("# %s\n\n"+
			"**Slug:** %s\n\n"+
			"## The Everyday Experience\n\n"+
			"%s\n\n"+
			"## The Hidden Math\n\n"+
			"%s\n\n"+
			"## Placement\n\n"+
			"- **Book:** %s\n"+
			"- **Part %d:** %s\n"+
			"- **Order:** %d\n",
			e.Title, e.Slug, e.Hook, e.HiddenMath, e.Book, e.Part, e.PartTitle, e.Order)

		metaContent := fmt.Sprintf("slug: %s\n"+
			"title: \"%s\"\n"+
			"book: %s\n"+
			"part: %d\n"+
			"part_title: \"%s\"\n"+
			"order: %d\n"+
			"status: pending\n"+
			"model: claude-sonnet-4-20250514\n"+
			"created: %s\n",
			e.Slug, e.Title, e.Book, e.Part, e.PartTitle, e.Order, now)

		slug := e.Slug
		mdPath := filepath.Join(baseDir, slug+".md")
		metaPath := filepath.Join(baseDir, slug+".meta.yaml")

		if err := os.WriteFile(mdPath, []byte(ideaContent), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "Error writing %s: %v\n", mdPath, err)
			os.Exit(1)
		}

		if err := os.WriteFile(metaPath, []byte(metaContent), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "Error writing %s: %v\n", metaPath, err)
			os.Exit(1)
		}

		fmt.Printf("Created: %s (.md + .meta.yaml)\n", slug)
	}

	fmt.Printf("\nTotal: %d essays scaffolded in %s/\n", len(essays), baseDir)

	// Summary by book
	counts := map[string]int{}
	for _, e := range essays {
		counts[e.Book]++
	}
	for _, b := range []string{"I", "II", "R"} {
		label := b
		if b == "R" {
			label = "Reserve"
		}
		fmt.Printf("  Book %s: %d essays\n", label, counts[b])
	}
}

func init() {
	_ = strings.TrimSpace
}
